# Generated by Django 5.1.7 on 2025-03-30 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_blog", "0002_alter_article_options_category_slug_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={
                "ordering": ["-pub_date"],
                "verbose_name": "Публікація",
                "verbose_name_plural": "Публікації",
            },
        ),
        migrations.AlterField(
            model_name="article",
            name="slug",
            field=models.SlugField(
                blank=True, unique_for_date="pub_date", verbose_name="Слаг"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(blank=True, unique=True, verbose_name="Слаг"),
        ),
    ]
